- app.py
- assets/style.css
- callbacks/control_bar.py
- callbacks/image_viewer.py
- components/control_bar.py
- components/image_viewer.py
- utils/data_utils.py
> Annotation features

- .gitignore
- app.py
- callbacks/control_bar.py
- callbacks/image_viewer.py
- components/control_bar.py
- components/image_viewer.py
- predeploy.py
- predeploy.sh
- project.toml
- requirements.txt
- utils/data_utils.py
After the tiled image source is introduced, a few changes need to be made, to accommodate for data source buckets, see the comment below:
https://github.com/mlexchange/mlex_highres_segmentation/blob/c711cf042e1e919910371f6082f1b8af77d541cc/callbacks/image_viewer.py#L38-L45
as well as changing this line to work with the new data:
https://github.com/mlexchange/mlex_highres_segmentation/blob/c711cf042e1e919910371f6082f1b8af77d541cc/callbacks/image_viewer.py#L14
> adds image selection controls

- callbacks/control_bar.py
- callbacks/image_viewer.py
- components/control_bar.py
- components/image_viewer.py
- utils/plot_utils.py
Removing unneeded controls and making minor style improvements to the image plot.
> Cleanup controls

- requirements-dev.txt
- utils/data_utils.py
add `SERVE_LOCALLY=True` to .env to make app talk to a local server (it will automatically download sample projects+images).
To run the server run `tiled serve directory --public data` in a separate terminal
> 🧑‍💻 add option to serve local tiled server

- app.py
- assets/style.css
- callbacks/image_viewer.py
- components/control_bar.py
- components/image_viewer.py
This PR will:
- Align all content of app to center of screen
- Align the image to center of its container
- Slightly reduce heigh and width of image to avoid scrolling inside container
> Center layout

- .github/workflows/publish-image.yml
- Dockerfile
- README.md
- docker-compose.yml
Makes progress towards resolving #4 for deployment at Spin with Spin being able to pull Docker images from [ghcr.io](ghcr.io)
> :whale: Add action to publish Docker image

- assets/functions.js
- callbacks/control_bar.py
Adds `filter` CSS support for Safari browsers.
> 🐛💄 safari css filter

- callbacks/control_bar.py
- components/control_bar.py
- components/image_viewer.py
features:
- the sidebar is hidable
- can be opened with an affix-ed button on the top left
- can be collapsed when opened
-it floats above the image (this might be changed in the future)
-image slice controls are not covered when the sidebar is opened
> ✨ Sidebar changes

- callbacks/control_bar.py
might need to be changed a bit when #74  is created / if drawer becomes solid and not an overlay
> 💄remove affix/controls overlap

- assets/style.css
- callbacks/image_viewer.py
- components/control_bar.py
- constants.py
- fixes drawer transparency to use the correct prompt setting (unique CSS didn't work on my end)
- add duration to the transition to make it feel nicer
- add arrow key binds to control image slices
> UI tweaks style fix

- app.py
- assets/functions.js
- assets/style.css
- callbacks/control_bar.py
- callbacks/image_viewer.py
- components/control_bar.py
- components/image_viewer.py
- constants.py
- mask_playground.ipynb
- utils/plot_utils.py
- Give the toolbar a little transparency and have it take up full height
- Move the selection slider to the toolbar so that it doesn't have to be resized and the image can take the whole space
- Move the keybinding info so that it doesn't overlap with the toolbar
> 💄 Minor UI updates

- callbacks/control_bar.py
- callbacks/image_viewer.py
- components/annotation_class.py
- components/control_bar.py
- components/image_viewer.py
- utils/annotations.py
- utils/data_utils.py
More quality of life improvements to the codebase.
> 🎨 add docstrings, remove imports, update comments

- callbacks/control_bar.py
- callbacks/image_viewer.py
- components/control_bar.py
- constants.py
- utils/annotations.py
removes code for 
- line width
- line and open freeform code in callbacks and key binds
- line and open freeform export types
> 🔥 remove line width

- app.py
- callbacks/segmentation.py
- components/control_bar.py
- utils/data_utils.py
Same things as #121 - but started from scratch since there were some messy merge conflicts.
> Segmentation updates v2

- callbacks/control_bar.py
- constants.py
- utils/plot_utils.py
when a class is selected it will create a notification
keybinds 1-9 select classes
if keybind is pressed and there are not that many classes, nothing happens
if the keybind for an already selected class is pressed, nothing happens
when a class is created and automatically selected - it creates a notification
when a class is deleted and a different class is selected - it creates notification
> ✨ select classes using keybinds

- callbacks/image_viewer.py
> 🐛 image flip on recentering

- callbacks/image_viewer.py
> Segmentation result improvements

- callbacks/image_viewer.py
Reverts mlexchange/mlex_highres_segmentation#151
> Revert "Segmentation result improvements"

- callbacks/image_viewer.py
Reverts mlexchange/mlex_highres_segmentation#152
I made a mistake reverting to a different branch, undoing that here. I meant to undo #149 due to it being potentially not finished. Apologies for the confusion
> Revert "Revert "Segmentation result improvements""

- assets/models.json
- callbacks/control_bar.py
- callbacks/image_viewer.py
- callbacks/segmentation.py
- components/control_bar.py
- requirements.txt
- utils/data_utils.py
- utils/plot_utils.py
This PR encompasses a number of fixes and extensions we came across while testing:
- Exports mask indices as a list of integers rather than a list of strings (this is also the way the model saves mask indices to Tiled)
- Adds the `num_classes` parameter to the inference job
- Extends the colormap by a gray color for unlabeled data and fixes a small bug in the color map scale when classes where deleted
- Autoscales the data with percentiles
- Passes the environment variables `RESULTS_DIR` as a new io parameter to the model as `models_dir`
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1207690415598274
> Diamond fixes

- callbacks/segmentation.py
This changes enable the possibility to save the human-readable user-selected job name with segmentations result, the result, making the result searchable and displayable in other contexts aside from the segmentation interface.
Companion PR to https://github.com/mlexchange/mlex_dlsia_segmentation_prototype/pull/34
Work by @taxe10.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1209745593156718
> Add `job_name` to inference job submission 

- .env.example
- callbacks/segmentation.py
- docker-compose.yml
This PR expands the flow types possible to be used to include:
- conda
- podman
- docker 
Flows launched through docker require https://github.com/mlexchange/mlex_prefect_worker/pull/24 to be merged.
Work by @taxe10.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1209745593156712
> Expand flow types to enable launching prefect flows with docker and podman
