mlexchange/mlex_highres_segmentation

.github/workflows/deploy.yaml
.github/workflows/prod-deploy.yml
.github/workflows/staging-deploy.yml
Procfile

I've passed along the required secrets to the ALS team to add to the github repo, otherwise should be good to go. I've added a new user for LBL to access our services server and given that user access to the "prod" environment of our prototype app.

Add continuous deployment to Dash server

---

callbacks/control_bar.py
callbacks/image_viewer.py
components/control_bar.py

Closes #26 
Adds buttons for freeform open/closed, circle, rectangle and "stop drawing" which switches it back to "pan" mode.

add annotation buttons

---

callbacks/control_bar.py
callbacks/image_viewer.py
components/control_bar.py

This PR adds 
- saving annotations across image slices
- saves visibility of annotations across slices
- saves dragmode (drawing) across slices
- disables dragmode (drawing) if the visibility of annotations is set to hidden
addresses #29 and it also fixes #19

Cross slice annotation saving

---

callbacks/image_viewer.py
components/image_viewer.py

Now the overlay will only display when the project is changed or when the image layer is changed
Note dmc.LoadingOverlay does not have `disabled` so I just change its zIndex

🚸 improve fig loading overlay to only show on img change

---

callbacks/image_viewer.py
components/control_bar.py

when image is changed, (and its size is different) zoom and pan will be preserved.
This will most likely need to be revisited because when compressed images are being sent, their sizes differ depending on the zoom, and thus we most likely won't be able to determine whether the image size is the same?
Also we will need to upgrade this with the same system we add where we ask for specific part of the image.
The image size needs to be there because if image1 is 2500x2500 and image2 is 200x200, if we zoom on image1 and then switch to image 2, it would most likely result in a white screen since we would be panned out of 200x200 bounds

🚸 preserve zoom and pan on image change

---

app.py
assets/style.css
callbacks/control_bar.py
callbacks/image_viewer.py
components/control_bar.py
utils/data_utils.py

Adds a garbage button to delete all annotations on the currently viewed frame, an eraser button (which does not work yet, waiting on Mojtaba to fix plotly bug), custom annotation class generator/deleter so that a user can choose a custom colour and label for an annotation class and then use them to annotate the graph. 
I'm leaving the hover bar in the graph until we get the eraser mode working

Update annotation UI

---

callbacks/image_viewer.py
components/control_bar.py

Proposing a slightly simpler approach to #51 -- addressing #41. I like this approach because it means that we don't have to update any callbacks when new controls are added into the existing sections on the sidebar. Since the loading spinner itself isn't visible it looks basically the same as if the controls are disabled.

🐛 disable controls using loadingOverlay

---

assets/style.css
callbacks/image_viewer.py
components/control_bar.py
components/image_viewer.py
utils/plot_utils.py

Adds viewfinder that shows the relative position on the graph
- the viewfinder is bounded to the figure layout, if the user zooms out/pans out the boundary will still be visible
- the boundary is carried over when the user selects a new image slice
- the viewfinder is downsampled so that it doesn't bottleneck networking
- the viewfinder is being Patched to improve performance. If required, this can be changed to clientside JS code, however, right now one move causes ~400B of network traffic which is negligible

✨ relative position viefinder

---

callbacks/control_bar.py
components/control_bar.py
utils/data_utils.py

This PR introduces loading and saving annotations.
- All existing project annotations can be saved by pressing a save button in the save/load/export menu
- if no annotations exist, it won't let the user save and will inform them that no annotations exist
- Users can go to the save/load/export menu and will see all saved annotations for that given user and the project they currently have selected. 
- if the project contains no new annotations it will inform the user by saying so
- when a user loads the annotations, the modal will be closed, and all annotations are loaded into the "annotation-store", figure if the data contains annotations for the currently selected slice, it will update the figure with those annotations

✨ Session loading saving

---

app.py
assets/functions.js
assets/style.css
callbacks/image_viewer.py
components/image_viewer.py
utils/plot_utils.py

- Add back full screen graph feature.
- Adjust view-finder dimensions for none square images
- Clean up redundant callback firings that keep re-rendering figure
Note: To avoid the image-viewer from re-rendering multiple times, added a dcc.Store that will save screen size only once on first load and moved the client side canvas resizer to a backend function the main renger_image callback will use.

Resize plot to full-screen

---

callbacks/image_viewer.py
callbacks/segmentation.py
requirements.txt
utils/data_utils.py

This updates the version of Tiled to the latest release.
In this release, tiff-sequences are added to the client tree in a different way than before and the retrieval of data is thus now wrapped in an additional function that makes sure we always still retrieve an array.
The PR also prepares for the server update on Spin where we will store additional data along-side the reconstructed data (e.g. raw data from the detector images, user-specific data such as masks and job results) and thus accesses only the `reconstruction` container to populate the project drop-down.
⚠️ Merging this PR needs to coordinated with the Server update as Tiled server and client versions need to be compatible.

⬆️ Update version of Tiled and adopt new server structure

---

tests/unit/test_control_bar.py
utils/data_utils.py

👽️ bump up timeout

---

.github/workflows/staging-deploy.yml
app.py
callbacks/control_bar.py
callbacks/image_viewer.py
callbacks/segmentation.py
components/control_bar.py
components/image_viewer.py
pyproject.toml
requirements-dev.txt
tests/unit/test_control_bar.py
utils/annotations.py
utils/data_utils.py
utils/plot_utils.py

Minor quality of life enhancement to sort import statements throughout the codebase.

Apply isort

---

app.py
assets/style.css
callbacks/control_bar.py
callbacks/image_viewer.py
components/annotation_class.py
components/control_bar.py
requirements.txt

This PR allows a user to modify the color of a class after it has been created. This requires a small refactor to the logic as the code was using the color as the class ID (thinking this was immutable), so now using uuid() instead to create class Ids.
Note: the color picker is now a dbc component instead of dmc.

Change class color

---

callbacks/control_bar.py
components/annotation_class.py
components/control_bar.py

- deletes the ability for a user to delete the last annotation class 
- removes loading overlay on sidebar so it doesn't trigger every time a user types
Didn't spend time on modal styling (assuming this will be done later for all the modals)

Prevent last class deletion

---

utils/annotations.py

*New*
- fixed ellipse annotation mask creation
*Checked existing features*
- overlapping works fine as is, the annotations on "top" will be on top (so long the order of the annotations in the storage remains as is (eg. new stuff is appended to the existing list at the end))
- Out-of-bounds works too with existing code 
- annotations entirely created outside are not included
- annotations that only have "parts" going outside are correctly cut out

Annot exporting improved

---

callbacks/control_bar.py
callbacks/image_viewer.py
components/control_bar.py
constants.py
utils/plot_utils.py

This PR adds a dropdown with the currently annotated slices. When a slice has annotations on it, this dropdown gets populated so the user can easily find which slices were annotated.
Implementation notes:
- When a user selects a slice to jump to, the dropdown value clears after it has been selected. This is to avoid confusion when a user goes to a different slice, there is no mismatch between the current slice and the slice in the dropdown. 
- This dropdown gets updated every time an annotation is drawn, when a class is deleted, when all annotations are deleted on a slice (and when a specific annotation is deleted via the eraser).
- May need to rework/rephrase the UI
Closes #122

Add annotated slice dropdown

---

assets/functions.js

Adds an event listener to the slice slider which removes the focus after interaction, this way it won't be triggered twice in the rare case described in the bug

🐛 remove focus from slider

---

.gitignore
README.md
app.py
callbacks/control_bar.py
docker-compose.yml
requirements.txt
tiled_serve_dir.sh
utils/data_utils.py

This PR groups some minor changes in relation to the deployment on Nersc. Most importantly it adds the basic auth wrapper, for now with a single username-password pair.
Additionally the following minor changes are included:
* Rename `API_KEY` to `TILED_API_KEY` to prepare for adding other keys (e.g. to Splash ML)
* Update the `TILED_URI` to `https://tiled-seg.als.lbl.gov` in `README.md`
* Make it possible for `EXPORT_FILE_PATH` to be an environment variable
* Add missing volume mount for `constants.py` in `docker-compose.yml`
* Ignore differently named Python environments `*env/`

Nersc deployment adaptations (Auth, Environment variables)

---

callbacks/control_bar.py
components/annotation_class.py
components/control_bar.py
components/image_viewer.py
utils/plot_utils.py

These styling typos were causing a lot of errors in the JS console making it hard to debug. 
Inline styles in Dash have to be camelCase and not kebab-case (although both will work).

small fixes for JS console errors

---

assets/style.css
callbacks/image_viewer.py
components/control_bar.py
components/image_viewer.py

Let user disable/enable the viewfinder
todo in the future: once the user loading data is implemented, save the viewfinder toggle state and load it when the user returns. Eg when they disable it and come back, it should be automatically disabled

Viewfinder toggle

---

callbacks/control_bar.py
callbacks/image_viewer.py

BugFix:
- annoation toolbar is disabled after using the slice selector 
- slice selector was not getting cleared after selecting same slice user is currently on
Added:
- loading overlay when a user jumps to a slice using the dropdown

bugfix + adding loading overlay

---

callbacks/control_bar.py
components/control_bar.py

When a user selects pan and zoom mode, the shapes are no longer editable (you cannot resize or drag them).
https://www.loom.com/share/795fef53c041483fbf153880269f4a68

disable shape editing during pan/zoom mode

---

.dockerignore
callbacks/control_bar.py
callbacks/image_viewer.py
callbacks/segmentation.py
components/annotation_class.py
components/control_bar.py
examples/plot_mask.py
examples/requirements.txt
requirements.txt
utils/annotations.py
utils/data_utils.py
utils/plot_utils.py

This PR makes the following changes:
- Introduces a new class `TiledMaskHandler` for handing mask loading and exporting calls. Currently this includes some legacy file-based code to be removed in the future.
- With that new class, seperates data access into input data, masks, and segmentation results (all of which may live on different Tiled servers)
- Pixelated masks are written to Tiled under `MASK_TILED_URI` + `/USER_NAME/project_name/annotation_hash`. This uri holds the meta data and an additional `mask` child contains the actual pixelated mask. This was original done to support writing annotations meta data for loading, without having to write pixelated masks. The writing happens upon job submission for model training.
- To avoid writing the same mask again (e.g. if no changes have …

Save pixelated masks to Tiled

---

assets/models.json
callbacks/control_bar.py
utils/data_utils.py

This PR validates the string parameters `weights` and `dilation_array` to have the correct format, such that they can be parsed as expected in mlexchange/mlex_dlsia_segmentation_prototype#12, and checks if class labels are non-empty.
Additionally, this adds parameters `qlty_step`, `qlty_window`, `qlty_border` for use of [`qlty`](https://github.com/phzwart/qlty) and extends a bug fix that wasn't fully followed through in 6193c53.

Add string parameter validation and `qlty` parameters

---

callbacks/segmentation.py
utils/prefect.py

This PR updated the query-related functions according to mlexchange/mlex_prefect_worker#16 In particular, it adds:
- Retrieving children flow run ids according to a given parent flow run id. These are sorted according to `START_TIME_ASC` by default, with the child flow that started first being at the beginning of the list
- Minor change to query function, such that it can be used for both (1) retrieving flows by names, and (2) querying children flows

Update prefect query functions
